### ISSUE TITLE
io.js still broken

### ISSUE THREAD

**Issue by bastimeyer** [mllrsohn/node-webkit-builder#201]
Despite the fix of #197, io.js still doesn't work correctly. We've just fixed the uncaught TypeError which prevented the execution. I thought it was working again, because I was able to build my application like before while using nodejs.

What I did not test was the nw.js cache download and archive extraction.
The archive gets properly downloaded, but it hangs afterwards (with 100% CPU usage) while trying to extract it. The file structure of the cache folder is also messed up and the filesize of the executable is only 64KiB.

Tested with io.js v1.4.2 and nw.js v0.11.6 and v0.12.0 on linux64...

```
.:
total 440K
-rw-r--r-- 1 basti basti  64K Mar  6 13:50 credits.html
-rw-r--r-- 1 basti basti  64K Mar  6 13:50 icudtl.dat
-rwxr-xr-x 1 basti basti  64K Mar  6 13:50 libffmpegsumo.so*
drwxr-xr-x 2 basti basti 4.0K Mar  6 13:50 locales/
drwxr-xr-x 3 basti basti 4.0K Jan 21 07:52 node-webkit-v0.11.6-linux-x64/
-rwxr-xr-x 1 basti basti  64K Mar  6 13:50 nw*
-rw-r--r-- 1 basti basti  64K Mar  6 13:50 nw.pak
-rwxr-xr-x 1 basti basti  64K Mar  6 13:50 nwsnapshot*

./locales:
total 0

./node-webkit-v0.11.6-linux-x64:
total 99M
-rw-rw-r-- 1 basti basti 810K Jan 21 07:52 credits.html
-rw-rw-r-- 1 basti basti  10M Jan 21 07:52 icudtl.dat
-rwxr-xr-x 1 basti basti 4.5M Jan 21 07:52 libffmpegsumo.so*
drwxr-xr-x 2 basti basti  12K Nov 26 06:23 locales/
-rwxr-xr-x 1 basti basti  70M Jan 21 07:52 nw*
-rw-rw-r-- 1 basti basti 5.6M Jan 21 07:52 nw.pak
-rwxr-xr-x 1 basti basti 8.6M Jan 21 07:52 nwsnapshot*

./node-webkit-v0.11.6-linux-x64/locales:
total 636K
-rw-r--r-- 1 basti basti 15 Nov 26 06:23 am.pak
[all the other .pak files]
```

**Comment by bastimeyer** [comment]
Ok, found the fix for that. It was another dependency issue.
@adam-lynch 
Could you please update the dependency of `ncp` in `graceful-ncp` to `^2.0.0`?
The issue was fixed here https://github.com/AvianFlu/ncp/commit/b920f5366b51ba766cc9c7e74a18704fd246b300 (the process.version regexp failed, but is now removed) and they also bumped their version afterwards to `2.0.0`.

**Comment by adam-lynch** [comment]
Done

**Comment by bastimeyer** [comment]
Thanks, but I think you forgot to update `graceful-fs-extra` as well (now that you've also bumped the version of `graceful-ncp`)... The grunt repo is also pointing to an invalid version... :disappointed: 
https://github.com/mllrsohn/grunt-node-webkit-builder/commit/8fb50f7a3cd2c5a9c471be56d71ed529b7d5906d

```bash
npm cache clean
npm install grunt-node-webkit-builder
```
```
grunt-node-webkit-builder@1.0.1 node_modules/grunt-node-webkit-builder
└── node-webkit-builder@1.1.0 (platform-overrides@1.0.1, inherits@2.0.1, progress@1.1.8, rcedit@0.2.0, temp@0.7.0, semver@2.3.2, optimist@0.6.1, graceful-ncp@1.0.0, graceful-fs-extra@1.0.4, tar-fs@0.3.3, bluebird@1.2.4, simple-glob@0.1.0, winresourcer@0.9.0, lodash@2.4.1, rimraf@2.3.1, decompress-zip@0.0.8, archiver@0.13.1, update-notifier@0.1.10, request@2.40.0, plist@1.1.0)
```

**Comment by adam-lynch** [comment]
Ah! graceful-fs-extra 1.0.5 & grunt-node-webkit-builder 1.0.2 published. Try again?

**Comment by bastimeyer** [comment]
Worked, ty...

**Comment by taktran** [comment]
@bastimeyer did you get it working with nwjs 0.12.0 and iojs 1.4.2, on osx?
